In [1]:
import pandas as pd

# SYMPTOMS ANALYSIS

In [12]:
df=pd.read_csv("4_1_vaers_k_means_clusters_scaling.csv")
df_s=df[df.columns[14:265]]

#seleziono il modello
df_s['Cluster_Label_5']=df['Cluster_Label_5'].tolist()
df_grouped=df_s.groupby(['Cluster_Label_5']).sum()

l_shapes=[]

for i in range(5):
    l_shapes.append(len(df[df['Cluster_Label_5']==i]))

<ipython-input-12-9002bf05db7c>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_s['Cluster_Label_5']=df['Cluster_Label_5'].tolist()

In [13]:
for c in df_grouped.columns:
    for i in range(5):
        df_grouped[c]=df_grouped[c].astype(float)
        val=round((df_grouped[c][i]/l_shapes[i])*100,2)
        df_grouped[c][i]=val
        
#df_grouped.to_csv("table.csv")

df_grouped

<ipython-input-13-a1c486eb2401>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_grouped[c][i]=val

,Headache,Chills,Pyrexia,Fatigue,Pain,Nausea,Dizziness,Pain in extremity,Myalgia,Injection site pain,...,Dyspnoea exertional,Bone pain,Haemorrhage,Metabolic function test normal,Appendicitis,Blood urea increased,Heart rate irregular,Petechiae,Blister,COUNT_SYMP
Cluster_Label_5,,,,,,,,,,,,,,,,,,,,,
0,3.21,4.15,9.06,5.85,2.08,3.40,3.21,1.70,1.32,0.94,...,0.75,0.00,0.75,0.19,0.94,1.70,0.00,1.13,0.19,350.00
1,44.71,35.43,30.04,35.49,26.96,27.34,21.20,16.88,17.11,15.19,...,0.63,0.75,0.24,0.59,0.21,0.38,0.49,0.28,0.21,736.81
2,4.61,3.39,3.95,3.58,2.92,3.39,2.07,3.30,1.41,2.07,...,0.47,0.09,0.66,0.38,0.56,0.66,0.19,0.75,0.09,229.85
3,5.42,1.95,3.53,2.90,2.11,1.73,4.78,3.35,2.75,2.86,...,0.03,0.01,0.19,0.01,0.10,0.02,0.03,0.11,0.16,133.63
4,22.09,16.56,17.50,14.98,15.20,11.84,10.17,9.07,8.74,9.26,...,0.11,0.16,0.16,0.20,0.27,0.18,0.25,0.18,0.28,385.07

In [14]:
df_grouped.drop("COUNT_SYMP",axis=1,inplace=True)

In [15]:
print("Cluster 0: deboli")
df_grouped.transpose()[0].sort_values(ascending=False).head(10)

Cluster 0: deboli

Asthenia                    12.83
Dyspnoea                    12.64
Death                       11.70
COVID-19                    11.51
Pyrexia                      9.06
SARS-CoV-2 test positive     8.30
Condition aggravated         7.55
Computerised tomogram        6.79
Blood test                   6.79
Intensive care               5.85
Name: 0, dtype: float64